server:
  port: 8080
  error:
    whitelabel:
      enabled: false 

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/books-market-db
    username: user
    password: password
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

attachments:
  connection:
    url: http://localhost:9000
    access-key: user 
    secret-key: password
    type: minio
  temporary-bucket: tmp
  permanent-bucket: perm

logging:
  level:
    root: info
    web: info
