server:
  port: 8080
#  DB
spring:
  datasource:
    url:
    username:
    password:
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate.ddl-auto: create-drop
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
#jwt
jwt:
  secret: