version: '2'

services:
  app:
    image: 'books-market:latest'
    build:
      context: .
    container_name: app
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/books-market-db
      - SPRING_DATASOURCE_USERNAME=user01
      - SPRING_DATASOURCE_PASSWORD=password01
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:14.5-alpine'
    container_name: db
    environment:
      - POSTGRES_DB=books-market-db
      - POSTGRES_USER=user01
      - POSTGRES_PASSWORD=password01
